services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pb
    container_name: fztezgiacem-pb
    restart: unless-stopped
    environment:
      PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY:-defaulthardcodedkey}
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8090/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    container_name: fztezgiacem-web
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DOMAIN_NAME=localhost
    depends_on:
      - pocketbase
